require.config({
	baseUrl:"/",//基本路径
	paths:{
		"jquery":"/wawsai/lib/jquery-1.12.4.min",//["https://code.jquery.com/jquery-1.12.4.min","lib/jquery-1.12.4.min"],
		"cookie":"/wawsai/lib/jquery.cookie",
		"load":"/wawsai/js/loadHeaderFooter",
		"carcousl":"/wawsai/lib/carousel",
		"template":"/wawsai/lib/template",
		"zoom":"/wawsai/lib/jquery.elevateZoom-2.2.3.min"
	}
});
